### ISSUE TITLE
请求支持安卓14

### ISSUE THREAD

**Issue by Mubai-meng** [dantmnf/PseudoDCDimming#10]
安卓14无法正常使用了，软件里的数值都已经无法显示了

**Comment by Ptilopsis01** [comment]
奇怪，我更新完系统也是用不了了，但是看作者更新里又有安卓14支持，难道是因为hyperos么

**Comment by dantmnf** [comment]
请提供一下 ROM 信息以及重启后的 LSPosed 日志。

另外我这边也只在近似原生的 ROM 上测试过，不保证魔改 ROM 能用，可以去试试另一个设置极暗的（

**Comment by Mubai-meng** [comment]
> 请提供一下 ROM 信息以及重启后的 LSPosed 日志。
> 
> 另外我这边也只在近似原生的 ROM 上测试过，不保证魔改 ROM 能用，可以去试试另一个设置极暗的（

应该是hyperos的原因，算了算了，先不用了
